### ISSUE TITLE
Copy of an image is already annotated(Add ability to annotate multiple copies of image)

### ISSUE THREAD

**Issue by sid22m** [djaodjin/djaodjin-annotate#23]
When I initialize the plugin with an image abc.jpeg and edit it. Now if I push the same image(abc.jpeg), it is already annotated with annotations of original one. Also annotations in any one copy is reflected in other copies and original image

**Comment by StephaneRob** [comment]
@sid22m I'm going to add the ability to annotate multiple copies of image.
To push image it will be possible to use:

- ```$('#myCanvas').annotate("push", "images/test.jpg");```: If image exists an id will be created, use ```annotate-image-added``` event to build the image selector it will still be possible to 


- ```$('#myCanvas').annotate("push", {id:"unique_identifier", path:"images/test.jpg"});```: push an image with an id, this will allow you to build image selector by 

You will be able to choose which attribute you want to use to select image by initialise annotate like this:

```javascript

$('#myCanvas').annotate({
    ...
    idAttribute: "my_attribute"
    ...
});
```
In your code replace ```data-path="{{image.url}}"``` ```my_attribute="{{image.id}}"``` (on image selector). Will fix #24

**Comment by sid22m** [comment]
Can you provide JSfiddle??

**Comment by StephaneRob** [comment]
@sid22m fix pushed. Let me know if you have any problem.

**Comment by sid22m** [comment]
@StephaneRob Its still not working with copy of image http://jsfiddle.net/te7rexkt/3/

**Comment by sid22m** [comment]
@StephaneRob New update is not working for me. Here's the fiddle : http://jsfiddle.net/te7rexkt/6/

**Comment by StephaneRob** [comment]
Here is a working fiddle. http://jsfiddle.net/1Lf9htL5/

If you build image selector by yourself (it's your case), you need to provide image object:

```javascript
$scope.imageList = [
    {id: "unique_identifier", path: "your image path or url"},
    {....}
]
```
The id must be unique.
The image selector must use the idAttribute to select image id, if default idAttribute ('id') option

```html
id="{{image.id}}"
```

if custom idAttribute (ex: idAttribute: "data-image-id"):

```html
data-image-id="{{image.id}}"
```

**Comment by StephaneRob** [comment]
@sid22m let me know if it's good.

**Comment by sid22m** [comment]
@StephaneRob  Thanks! I got it now. Its working
